#!/usr/bin/env python3
"""
cil2te.py - convert MTK proprietary vendor_sepolicy.cil into .te source
files and a genfs_contexts addendum for BOARD_VENDOR_SEPOLICY_DIRS.

AOSP's Soong build rebuilds vendor_sepolicy.cil from .te sources and
overwrites the proprietary copy, so the ~14k rules from the MTK blob
never reach the device. This script converts them back to .te form.

See HEADER.txt in vendor_mtk_prebuilt/ for full usage and flag details.

Key transformations:
  - Strip _202404 version suffixes (secilc aliases for plat_pub_policy)
  - Rename base_typeattr_NNN -> mtk_typeattr_NNN (avoid collisions)
  - Suppress type decls already in --known sources
  - Drop roletype (implicit in .te), neverallow (CTS hygiene only)
  - Split genfscon entries to a separate output file

Synthetic attribute resolution: base_typeattr_NNN attrs of the form
(and (POSITIVE) (not (EXCLUDED))) are resolved to just POSITIVE. This
is overly permissive for the excluded set but safe in practice since
the excluded domains are sandbox/test types that should not touch
vendor surfaces. Neverallows are dropped entirely so the exclusion
list is irrelevant for enforcement.
"""

import argparse
import os
import re
import sys
from typing import List, Tuple


# ---------------------------------------------------------------------------
# S-expression tokenizer + parser
# ---------------------------------------------------------------------------

TOKEN_RE = re.compile(r'\(|\)|"[^"]*"|[^\s()]+')


def tokenize(line: str) -> List[str]:
    return TOKEN_RE.findall(line)


def parse(tokens: List[str]):
    """Parse a single s-expression. Returns (node, rest)."""
    if not tokens:
        raise ValueError("empty token stream")
    tok = tokens[0]
    if tok == '(':
        out = []
        rest = tokens[1:]
        while rest and rest[0] != ')':
            node, rest = parse(rest)
            out.append(node)
        if not rest:
            raise ValueError("unterminated s-expr")
        return out, rest[1:]   # drop ')'
    if tok == ')':
        raise ValueError("unexpected ')'")
    return tok, tokens[1:]


# ---------------------------------------------------------------------------
# Suffix / name rewriting
# ---------------------------------------------------------------------------

# Strip _202404 anywhere it appears as a complete suffix on an identifier.
# We bind to a word-boundary on the right so that `foo_202404_bar` (which
# does not exist in the input) wouldn't be mangled.
SUFFIX_RE = re.compile(r'_202404(?=[\s)("\']|$)')

# Rename autogenerated synthetic attributes so they live in our namespace.
BASE_TA_RE = re.compile(r'\bbase_typeattr_(\d+)\b')


def normalize(s: str) -> str:
    s = SUFFIX_RE.sub('', s)
    s = BASE_TA_RE.sub(r'mtk_typeattr_\1', s)
    return s


def normalize_node(node):
    if isinstance(node, str):
        return normalize(node)
    return [normalize_node(n) for n in node]


# CIL allows dashes in type names but .te / checkpolicy rejects them.
# These dash-named types were already dropped from file_contexts, so
# nothing on disk carries these labels; safe to skip matching rules.
DASH_IDENT_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*-[A-Za-z0-9_-]+$')


def has_dash_identifier(node) -> bool:
    if isinstance(node, str):
        # Strings inside cil are either bare identifiers or "quoted paths".
        # Quoted paths (genfscon) start with `"` - skip those since
        # them just because the path contains a dash like /sys/dev/foo-bar.
        if node.startswith('"'):
            return False
        return bool(DASH_IDENT_RE.match(node))
    return any(has_dash_identifier(n) for n in node)


# ---------------------------------------------------------------------------
# Per-construct emitters
# ---------------------------------------------------------------------------

def fmt_perms(perms) -> str:
    """A perm list in cil is a flat list of strings. Render as a te {…} set."""
    if isinstance(perms, str):
        return perms
    return '{ ' + ' '.join(perms) + ' }'


def fmt_classes(cls) -> str:
    if isinstance(cls, str):
        return cls
    # multi-class form: emit as { c1 c2 }
    return '{ ' + ' '.join(cls) + ' }'


def emit_av(kind: str, node) -> str:
    """Emit allow/dontaudit/neverallow: (kind src tgt (class (perm ...)))."""
    if len(node) != 4:
        return f'# UNHANDLED {kind}: {node}'
    _, src, tgt, cp = node
    if not isinstance(cp, list) or len(cp) != 2:
        return f'# UNHANDLED {kind} class/perm: {node}'
    cls, perms = cp
    return f'{kind} {src} {tgt}:{fmt_classes(cls)} {fmt_perms(perms)};'


def emit_typetransition(node) -> str:
    # (typetransition src tgt class new) or with optional name
    # (typetransition src tgt class "name" new)  -- file-name based
    if len(node) == 5:
        _, src, tgt, cls, new = node
        return f'type_transition {src} {tgt}:{cls} {new};'
    if len(node) == 6:
        _, src, tgt, cls, name, new = node
        # Preserve quotes around name; te grammar requires them.
        return f'type_transition {src} {tgt}:{cls} {new} {name};'
    return f'# UNHANDLED typetransition: {node}'


def emit_typeattributeset(node) -> List[str]:
    # (typeattributeset attr (t1 t2 ...))  OR  (typeattributeset attr t1)
    if len(node) != 3:
        return [f'# UNHANDLED typeattributeset: {node}']
    _, attr, types = node
    if isinstance(types, str):
        types = [types]
    out = []
    for t in types:
        if isinstance(t, list):
            # Set-op body from secilc expansion; handled by
            # substitute_synthetic() pass. No-op here.
            return []
        if (t, attr) in NEVERALLOW_SKIP_TYPEATTR:
            # Skip the (type, attribute) pair: would widen a plat-side
            # attribute into a neverallow violation. See the
            # NEVERALLOW_SKIP_TYPEATTR docstring above.
            continue
        out.append(f'typeattribute {t} {attr};')
    return out


def fmt_xperm_set(perms) -> str:
    """allowx perm set: a flat list of either bare numerics or
       (range LO HI) sublists. Render as te xperm braces."""
    parts = []
    for p in perms:
        if isinstance(p, list) and len(p) == 3 and p[0] == 'range':
            parts.append(f'{p[1]}-{p[2]}')
        elif isinstance(p, str):
            parts.append(p)
        else:
            parts.append(f'#?{p}')
    return '{ ' + ' '.join(parts) + ' }'


def emit_allowx(node) -> str:
    # (allowx src tgt (ioctl class (perms…)))
    if len(node) != 4:
        return f'# UNHANDLED allowx: {node}'
    _, src, tgt, body = node
    if not isinstance(body, list) or len(body) != 3 or body[0] != 'ioctl':
        return f'# UNHANDLED allowx body: {node}'
    _ioctl, cls, perms = body
    return f'allowxperm {src} {tgt}:{cls} ioctl {fmt_xperm_set(perms)};'


def emit_typealias(name: str, target: str) -> str:
    return f'typealias {target} alias {name};'


# ---------------------------------------------------------------------------
# Neverallow-violation filter (post-substitute_synthetic).
#
# After substitution, synthetic attrs of shape (and (domain) (not (...)))
# collapse to bare `domain`, producing over-broad rules that trip AOSP
# CTS-hygiene neverallows in domain.te. Filter drops rules whose src/tgt
# is bare `domain` after substitution.
#
# hal_keymint_strongbox_exec: no file_contexts label on disk; skip all
# rules referencing this type to avoid false-positive neverallow hits.
SKIP_BARE_DOMAIN_SIDES = True
NEVERALLOW_SKIP_TYPES = {
    'hal_keymint_strongbox_exec',
}

# Pair-based skip list: (source_set, target_set) tuples. Rules whose
# src is in source_set AND tgt is in target_set are dropped to avoid
# Treble coredomain-boundary neverallow violations (domain.te, isolated_app_all.te).

# (type, attribute) pairs to drop from typeattributeset. The proprietary
# cil wrongly attaches ff_service and remosaic_daemon_service to
# vndservice_manager_type, which would widen plat-side attribute rules
# into domain.te:928 violations. Per-domain allow rules still provide access.
NEVERALLOW_SKIP_TYPEATTR = {
    ('ff_service', 'vndservice_manager_type'),
    ('remosaic_daemon_service', 'vndservice_manager_type'),
}

NEVERALLOW_SKIP_RULES = [
    # Category A: vendor logger/crash daemons -> core data/exec/sock types.
    (
        {'emdlogger', 'mobile_log_d', 'mdlogger', 'aee_core_forwarder',
         'connsyslogger', 'vtservice', 'netdiag'},
        {'logcat_exec', 'crash_dump', 'logdr_socket',
         'logtemp_data_file', 'mdlog_data_file', 'aee_core_data_file',
         'aee_exp_data_file', 'media_rw_data_file', 'logmisc_data_file',
         'data_tmpfs_log_file', 'consyslog_data_file', 'net_data_file'},
    ),
    # Category B: core domains connecting to vendor logger unix/tcp/udp
    # sockets. Violates domain.te:952.
    (
        {'platform_app', 'netd'},
        {'mdlogger', 'netdiag', 'connsyslogger', 'emdlogger',
         'mobile_log_d'},
    ),
    # Category C: appdomain / isolated_app finding vendor service_manager
    # or hwservice_manager targets. Violates isolated_app_all.te 54/71.
    (
        {'isolated_app', 'appdomain'},
        {'mtk_hal_gpuserv_service', 'mtk_hal_mms_service',
         'mtk_hal_mbrain_service', 'hidl_manager_hwservice',
         'mtk_safe_service_manager_type'},
    ),
    # Category D: core tracing / dumpstate tools finding vendor
    # ff_service / remosaic_daemon_service. Violates domain.te:928.
    (
        {'atrace', 'dumpstate', 'system_app', 'traceur_app'},
        {'ff_service', 'remosaic_daemon_service'},
    ),
]


def _node_refs_type(node, name: str) -> bool:
    if isinstance(node, str):
        return node == name
    if isinstance(node, list):
        return any(_node_refs_type(c, name) for c in node)
    return False


def should_skip_for_neverallow(node) -> str:
    """Return a non-empty reason string if the rule should be dropped,
       or '' to keep it. Applied to allow/dontaudit/typetransition/allowx
       after substitute_synthetic()."""
    if not isinstance(node, list) or len(node) < 3:
        return ''
    head = node[0]
    if head not in ('allow', 'dontaudit', 'typetransition', 'allowx'):
        return ''
    # Any reference to a skip-listed type: drop.
    for t in NEVERALLOW_SKIP_TYPES:
        if _node_refs_type(node, t):
            return f'skip_type:{t}'
    if SKIP_BARE_DOMAIN_SIDES:
        # Source or target is literally "domain" - over-broad.
        src, tgt = node[1], node[2]
        if src == 'domain' or tgt == 'domain':
            return 'bare_domain'
    # Pair-based skip table (Treble-hygiene / CTS neverallow categories).
    if isinstance(node[1], str) and isinstance(node[2], str):
        src, tgt = node[1], node[2]
        for src_set, tgt_set in NEVERALLOW_SKIP_RULES:
            if src in src_set and tgt in tgt_set:
                return f'skip_pair:{src}->{tgt}'
    return ''


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def load_known_types(path: str) -> set:
    """Scrape `type X;` and `attribute X;` declarations from a .te or
    vendor_sepolicy.conf file. Both formats use the same syntax:
        type foo;
        type foo, attr1, attr2;
        attribute bar;
    Returns the union of all declared names."""
    known = set()
    if not path or not os.path.exists(path):
        return known
    with open(path) as f:
        for line in f:
            line = line.strip()
            m = re.match(r'^type\s+([A-Za-z0-9_]+)\s*[,;]', line)
            if m:
                known.add(m.group(1))
            m = re.match(r'^attribute\s+([A-Za-z0-9_]+)\s*;', line)
            if m:
                known.add(m.group(1))
    return known


def load_known_types_multi(paths: list) -> set:
    known = set()
    for p in paths:
        known |= load_known_types(p)
    return known


def count_known_decls(path: str) -> dict:
    """Like load_known_types, but returns {name: occurrence_count}. Used
    to distinguish names that upstream declares (count >= 2 in a conf
    that also got our self-contribution rolled in) from names that only
    exist because of our prior install (count == 1)."""
    counts = {}
    if not path or not os.path.exists(path):
        return counts
    with open(path) as f:
        for line in f:
            line = line.strip()
            m = re.match(r'^type\s+([A-Za-z0-9_]+)\s*[,;]', line)
            if m:
                counts[m.group(1)] = counts.get(m.group(1), 0) + 1
                continue
            m = re.match(r'^attribute\s+([A-Za-z0-9_]+)\s*;', line)
            if m:
                counts[m.group(1)] = counts.get(m.group(1), 0) + 1
    return counts


def load_existing_type_transitions(path: str) -> set:
    """Extract `type_transition src tgt:cls new` rules already present in the
    upstream policy so we can suppress duplicates from the proprietary cil.

    Returns a set of normalized signature strings of the form
        "src tgt cls new"        - unnamed transitions
        "src tgt cls new name"   - filename transitions

    The proprietary blob and the upstream LineageOS sepolicy frequently
    overlap on common HAL hooks (wpa_supplicant socket, wifi_data_file/dir,
    etc.). checkpolicy treats two identical type_transitions as a duplicate
    declaration error rather than a no-op.
    """
    existing = set()
    if not path or not os.path.exists(path):
        return existing
    # Match both classic and filename forms.
    classic = re.compile(
        r'^\s*type_transition\s+(\S+)\s+(\S+)\s*:\s*(\S+)\s+(\S+)\s*;')
    named = re.compile(
        r'^\s*type_transition\s+(\S+)\s+(\S+)\s*:\s*(\S+)\s+(\S+)\s+"([^"]+)"\s*;')
    with open(path) as f:
        for line in f:
            m = named.match(line)
            if m:
                existing.add(' '.join(m.groups()))
                continue
            m = classic.match(line)
            if m:
                existing.add(' '.join(m.groups()))
    return existing


def collect_synthetic_attrs(cil_path: str) -> dict:
    """Pass 1: walk the cil and find every
       (typeattributeset mtk_typeattr_NNN (and (POSITIVE) (not (...))))
       mapping. Returns NNN_name -> positive_root_string."""
    mapping = {}
    with open(cil_path) as f:
        for raw in f:
            raw = raw.rstrip('\n')
            if 'base_typeattr_' not in raw or 'typeattributeset' not in raw:
                continue
            try:
                node, _ = parse(tokenize(raw))
            except Exception:
                continue
            node = normalize_node(node)
            if (not isinstance(node, list) or len(node) != 3
                    or node[0] != 'typeattributeset'):
                continue
            name = node[1]
            if not name.startswith('mtk_typeattr_'):
                continue
            body = node[2]
            # body is typically (and (POSITIVE) (not (excluded...)))
            # POSITIVE may be a single token or a list of tokens.
            positive = None
            if isinstance(body, list) and body and body[0] == 'and':
                if len(body) >= 2:
                    pos = body[1]
                    if isinstance(pos, str):
                        positive = pos
                    elif isinstance(pos, list) and pos:
                        # Single-element list: take its element.
                        # Multi-element: take the first; we'll lose precision
                        # on the rest but every observed case has exactly one.
                        positive = pos[0] if isinstance(pos[0], str) else None
            elif isinstance(body, str):
                positive = body
            elif isinstance(body, list) and len(body) == 1 and isinstance(body[0], str):
                positive = body[0]
            if positive:
                mapping[name] = positive
    return mapping


def substitute_synthetic(node, mapping: dict):
    """Recursively replace mtk_typeattr_NNN tokens with their resolved
       positive root from the mapping. Anything not in the mapping is
       left as-is (and will compile to an empty attribute we declare
       below)."""
    if isinstance(node, str):
        return mapping.get(node, node)
    return [substitute_synthetic(n, mapping) for n in node]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cil', required=True)
    ap.add_argument('--known', required=True, action='append',
                    help='File(s) to scrape `type X;` / `attribute X;` '
                         'decls from so that those names are NOT inferred '
                         'as new attributes. Pass at minimum the device '
                         'mtk_types.te plus the built vendor_sepolicy.conf '
                         '(which contains the full flattened AOSP + vendor '
                         'type universe). Repeatable.')
    ap.add_argument('--existing-conf',
                    help='vendor_sepolicy.conf to scan for existing '
                         'type_transition rules to dedupe against')
    ap.add_argument('--existing-genfs', action='append', default=[],
                    help='genfs_contexts file(s) to dedupe against; '
                         'pass multiple times')
    ap.add_argument('--installed-prefix',
                    help='Path to the directory where a PREVIOUS invocation '
                         'of this script installed its output (e.g. '
                         'device/rainx/theloop/sepolicy/vendor_mtk_prebuilt). '
                         'If set, any type_transition or genfscon entry '
                         'discovered in that prior output is SUBTRACTED '
                         'from the --existing-conf dedup set, so that the '
                         'dedup only strips entries that came from genuinely '
                         'external sources rather than from our own prior '
                         'run. Without this, subsequent regens become '
                         'non-idempotent: our previous output gets baked '
                         'into vendor_sepolicy.conf and then stripped as '
                         '"already present", emptying the file entirely.')
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    known = load_known_types_multi(args.known)
    print(f'[+] {len(known)} types known from {len(args.known)} source(s): '
          f'{args.known}', file=sys.stderr)

    # Idempotency: subtract type/attribute decls from our prior install,
    # but only for names NOT also declared by an upstream source. We
    # detect "also declared upstream" by walking each --known source that
    # is a vendor_sepolicy.conf (has occurrence counts; the conf will
    # already contain our own contribution concatenated in), and keeping
    # any name whose total count is >= 2 (we declared it + at least one
    # upstream did too). Names with count == 1 are sole-ours and are
    # safe to subtract from known so their decls get re-emitted.
    #
    # Without this split, a name like `aac_drc_prop` (declared by AOSP
    # base + wrongly declared as attribute by our prior install) would
    # be subtracted entirely, fall out of known on the next regen, and
    # get re-inferred as an attribute, producing the same duplicate
    # declaration error.
    if args.installed_prefix:
        self_te = os.path.join(args.installed_prefix, 'mtk_proprietary.te')
        self_known = load_known_types(self_te)
        if self_known:
            # Combined per-name counts across every --known source. Any
            # name whose total count is >= 2 has at least one non-self
            # decl (since our file contributes at most one per name).
            combined_counts = {}
            for p in args.known:
                for n, c in count_known_decls(p).items():
                    combined_counts[n] = combined_counts.get(n, 0) + c
            sole_self = {n for n in self_known
                         if combined_counts.get(n, 0) < 2}
            before = len(known)
            known -= sole_self
            print(f'[+] subtracted {before - len(known)} sole-self '
                  f'type/attribute decls (of {len(self_known)} total self '
                  f'decls; {len(self_known) - len(sole_self)} kept because '
                  f'also declared upstream)', file=sys.stderr)

    existing_tt = load_existing_type_transitions(args.existing_conf or '')
    if existing_tt:
        print(f'[+] {len(existing_tt)} existing type_transitions from conf',
              file=sys.stderr)

    # Subtract previously-installed self-contribution from the conf-derived
    # dedup set so regens stay idempotent.
    if args.installed_prefix:
        self_te = os.path.join(args.installed_prefix, 'mtk_proprietary.te')
        self_tt = load_existing_type_transitions(self_te)
        if self_tt:
            existing_tt -= self_tt
            print(f'[+] subtracted {len(self_tt)} type_transitions from '
                  f'previously-installed {self_te}',
                  file=sys.stderr)
            print(f'[+] {len(existing_tt)} external type_transitions to dedupe',
                  file=sys.stderr)

    # genfs_contexts dedupe set: keyed by "fs path".
    # Use --existing-genfs for upstream sources only; do NOT scrape the
    # conf (it contains our prior output, breaking idempotency).
    def _read_genfs(path):
        out = set()
        if not path or not os.path.exists(path):
            return out
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                parts = line.split()
                if len(parts) >= 3 and parts[0] == 'genfscon':
                    out.add(f'{parts[1]} {parts[2]}')
        return out

    existing_genfs = set()
    # Skip anything under --installed-prefix so our own prior output doesn't
    # poison the dedup set (same idempotency concern as TT dedup above).
    skip_paths = set()
    if args.installed_prefix:
        skip_paths.add(os.path.realpath(
            os.path.join(args.installed_prefix, 'genfs_contexts')))
    for gp in args.existing_genfs:
        if os.path.realpath(gp) in skip_paths:
            print(f'[+] skipping self-installed genfs source: {gp}',
                  file=sys.stderr)
            continue
        existing_genfs |= _read_genfs(gp)
    if existing_genfs:
        print(f'[+] {len(existing_genfs)} existing genfs entries to dedupe',
              file=sys.stderr)

    synth = collect_synthetic_attrs(args.cil)
    print(f'[+] {len(synth)} synthetic mtk_typeattr_NNN aliases resolved',
          file=sys.stderr)

    # Pre-pass: discover identifiers referenced anywhere in the cil and
    # work out which ones we need to forward-declare as attributes for
    # checkpolicy. CIL is happy to let `(typeattributeset some_attr ...)`
    # or even an `(allow X some_attr ...)` rule be the first sighting of
    # `some_attr`; .te is not.
    #
    # Strategy: collect every name that appears as:
    #   - the target of (typeattributeset NAME ...)
    #   - the source/target of any (allow|dontaudit|neverallow|typetransition|allowx)
    # Subtract the names that are explicitly declared as types via (type X)
    # or that already exist in `known`. Whatever remains is treated as a
    # vendor attribute that needs an `attribute X;` decl.
    used_names = set()
    declared_types_from_cil = set()
    with open(args.cil) as f:
        for raw in f:
            try:
                node, _ = parse(tokenize(raw))
            except Exception:
                continue
            node = normalize_node(node)
            if not isinstance(node, list) or not node:
                continue
            head = node[0]
            if head == 'type' and len(node) == 2:
                declared_types_from_cil.add(node[1])
            elif head == 'typeattributeset' and len(node) >= 2 \
                    and isinstance(node[1], str):
                used_names.add(node[1])
            elif head in ('allow', 'dontaudit', 'neverallow', 'allowx') \
                    and len(node) >= 3:
                # source / target: known type or attribute to declare.
                for pos in (node[1], node[2]):
                    if isinstance(pos, str) and pos != 'self':
                        used_names.add(pos)
            elif head == 'typetransition' and len(node) >= 5:
                for pos in (node[1], node[2], node[-1]):
                    if isinstance(pos, str):
                        used_names.add(pos)
    inferred_attrs = sorted(
        a for a in used_names
        if a not in known
        and a not in declared_types_from_cil
        and not a.startswith('mtk_typeattr_')
        # Drop dash-ident leftovers; those rules are skipped at emit time.
        and not DASH_IDENT_RE.match(a)
        # Filter obvious non-identifiers (`self`, perm names like `read`, etc.)
        and re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', a)
    )
    print(f'[+] {len(inferred_attrs)} attributes inferred from type/rule usage',
          file=sys.stderr)

    decl_lines = []   # type / attribute declarations (emitted first)
    te_lines = []     # rules (emitted after declarations)
    genfs_lines = []
    new_attrs = set()
    new_types = set()

    # Seed declarations with the inferred attribute set up front so they
    # exist before any rule that names them.
    for a in inferred_attrs:
        decl_lines.append(f'attribute {a};')
        new_attrs.add(a)
    skipped = {'neverallow': 0, 'roletype': 0, 'type_dup': 0,
               'unhandled': 0, 'dash_ident': 0,
               'bare_domain': 0, 'skip_type': 0, 'skip_pair': 0}

    # Pending typealias bookkeeping: (typealias X) declares the alias name,
    # (typealiasactual X Y) binds it to type Y. We need both to emit one te line.
    pending_alias = set()
    alias_pairs = []  # (alias, target)

    with open(args.cil) as f:
        for lineno, raw in enumerate(f, 1):
            raw = raw.rstrip('\n')
            if not raw.strip() or raw.lstrip().startswith(';'):
                continue
            try:
                tokens = tokenize(raw)
                node, rest = parse(tokens)
            except Exception as e:
                te_lines.append(f'# PARSE_ERR line {lineno}: {raw}  ({e})')
                skipped['unhandled'] += 1
                continue
            if rest:
                te_lines.append(f'# TRAILING line {lineno}: {raw}')
            node = normalize_node(node)
            node = substitute_synthetic(node, synth)
            if not isinstance(node, list) or not node:
                continue
            # Drop statements with dash-bearing identifiers (invalid in .te).
            if has_dash_identifier(node):
                skipped['dash_ident'] += 1
                continue
            head = node[0]

            # Drop resolved synthetic mtk_typeattr_NNN decls (substituted away).
            if head == 'typeattribute' and len(node) == 2 \
                    and node[1].startswith('mtk_typeattr_') \
                    and node[1] in synth:
                continue
            if head == 'typeattributeset' and len(node) >= 2 \
                    and isinstance(node[1], str) \
                    and node[1].startswith('mtk_typeattr_') \
                    and node[1] in synth:
                continue

            if head == 'type':
                # (type X)
                if len(node) == 2:
                    name = node[1]
                    if name in NEVERALLOW_SKIP_TYPES:
                        skipped['skip_type'] += 1
                        continue
                    if name in known or name in new_types:
                        skipped['type_dup'] += 1
                        continue
                    new_types.add(name)
                    decl_lines.append(f'type {name};')
                continue

            if head == 'typeattribute':
                # (typeattribute X) - declare attribute X.
                # Skip if already in known, already emitted, or a resolved
                # synthetic. Only emit genuinely new vendor attributes.
                if len(node) == 2:
                    name = node[1]
                    if name in known or name in new_attrs:
                        continue
                    if name.startswith('mtk_typeattr_'):
                        continue
                    new_attrs.add(name)
                    decl_lines.append(f'attribute {name};')
                continue

            if head == 'roletype':
                skipped['roletype'] += 1
                continue

            if head == 'neverallow':
                skipped['neverallow'] += 1
                continue

            if head == 'typeattributeset':
                # Skip typeattributeset entries that would wire a skip-listed
                # type into an attribute (e.g. hal_keymint_strongbox_exec into
                # exec_type / vendor_file_type).
                if len(node) >= 2 and isinstance(node[1], str) \
                        and node[1] in NEVERALLOW_SKIP_TYPES:
                    skipped['skip_type'] += 1
                    continue
                if len(node) >= 3:
                    tlist = node[2] if isinstance(node[2], list) else [node[2]]
                    if any(isinstance(t, str) and t in NEVERALLOW_SKIP_TYPES
                           for t in tlist):
                        skipped['skip_type'] += 1
                        continue
                te_lines.extend(emit_typeattributeset(node))
                continue

            # Neverallow-violation filter (bare domain, skip-listed types,
            # skip-listed src/tgt pairs).
            reason = should_skip_for_neverallow(node)
            if reason:
                if reason == 'bare_domain':
                    key = 'bare_domain'
                elif reason.startswith('skip_pair'):
                    key = 'skip_pair'
                else:
                    key = 'skip_type'
                skipped[key] += 1
                continue

            if head == 'allow':
                te_lines.append(emit_av('allow', node))
                continue
            if head == 'dontaudit':
                te_lines.append(emit_av('dontaudit', node))
                continue

            if head == 'typetransition':
                # Build the same signature shape as load_existing_type_transitions
                # so we can dedupe.
                if len(node) == 5:
                    sig = f'{node[1]} {node[2]} {node[3]} {node[4]}'
                elif len(node) == 6:
                    # node[4] is the filename, still wrapped in literal "..."
                    # because the cil tokenizer keeps the quotes; the dedupe
                    # signature wants the bare name to match the regex group
                    # in load_existing_type_transitions which strips them.
                    name = node[4].strip('"')
                    sig = f'{node[1]} {node[2]} {node[3]} {node[5]} {name}'
                else:
                    sig = None
                if sig and sig in existing_tt:
                    skipped.setdefault('tt_dup', 0)
                    skipped['tt_dup'] += 1
                    continue
                te_lines.append(emit_typetransition(node))
                continue

            if head == 'allowx':
                te_lines.append(emit_allowx(node))
                continue

            if head == 'typealias':
                # (typealias X) - alias declaration without target
                if len(node) == 2:
                    pending_alias.add(node[1])
                continue

            if head == 'typealiasactual':
                # (typealiasactual alias type)
                if len(node) == 3:
                    alias_pairs.append((node[1], node[2]))
                continue

            if head == 'genfscon':
                # (genfscon fs path (user role type ((s_lo) (s_hi))))
                if len(node) == 4:
                    fs, path, ctx = node[1], node[2], node[3]
                    # path is a quoted string
                    path_clean = path.strip('"')
                    key = f'{fs} {path_clean}'
                    if key in existing_genfs:
                        skipped.setdefault('genfs_dup', 0)
                        skipped['genfs_dup'] += 1
                        continue
                    if isinstance(ctx, list) and len(ctx) >= 3:
                        user, role, typ = ctx[0], ctx[1], ctx[2]
                        genfs_lines.append(
                            f'genfscon {fs} {path_clean}'
                            f'   u:{role}:{typ}:s0'
                        )
                        # Also insert into existing_genfs so duplicates
                        # *within* the proprietary cil get collapsed.
                        existing_genfs.add(key)
                continue

            # Anything else (handleunknown, classpermission, role, user, sid,
            # etc.) - silently dropped; base policy header, not imported.
            skipped['unhandled'] += 1

    # Emit any typealiasactual pairs
    for alias, target in alias_pairs:
        te_lines.append(emit_typealias(alias, target))

    os.makedirs(args.out, exist_ok=True)
    te_path = os.path.join(args.out, 'mtk_proprietary.te')
    gf_path = os.path.join(args.out, 'mtk_proprietary_genfs.txt')

    header = (
        '# AUTO-GENERATED by device/rainx/theloop/sepolicy/tools/cil2te.py\n'
        '# DO NOT HAND-EDIT. Re-run the converter (see HEADER.txt) instead.\n'
        '# Source: vendor/rainx/theloop/proprietary/vendor/etc/selinux/vendor_sepolicy.cil\n'
        '#\n'
        '# This file restores the ~14 000 rules that the AOSP build silently\n'
        '# discards (Soong rebuilds vendor_sepolicy.cil from BOARD_VENDOR_SEPOLICY_DIRS\n'
        '# and overwrites the proprietary copy installed by proprietary-files.txt).\n'
        '# Without it, every MTK vendor daemon runs as u:r:init:s0 instead of its\n'
        '# proper domain.\n'
        '#\n'
    )

    with open(te_path, 'w') as f:
        f.write(header)
        f.write('\n')
        f.write('# ---- type declarations (emitted before any rule that '
                'might forward-reference them) ----\n')
        f.write('\n'.join(decl_lines))
        f.write('\n\n# ---- rules ----\n')
        f.write('\n'.join(te_lines))
        f.write('\n')

    with open(gf_path, 'w') as f:
        f.write('# AUTO-GENERATED genfs_contexts addendum from cil2te.py.\n')
        f.write('# Cat onto sepolicy/vendor/genfs_contexts after dedup.\n')
        f.write('\n'.join(genfs_lines))
        f.write('\n')

    print(f'[+] wrote {len(te_lines)} te statements -> {te_path}', file=sys.stderr)
    print(f'[+] wrote {len(genfs_lines)} genfs lines  -> {gf_path}', file=sys.stderr)
    print(f'[+] new types declared:      {len(new_types)}', file=sys.stderr)
    print(f'[+] new attributes declared: {len(new_attrs)}', file=sys.stderr)
    print(f'[+] skipped:                 {skipped}', file=sys.stderr)


if __name__ == '__main__':
    main()
